// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package social_api_ws

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type IdReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdReq) Reset()         { *m = IdReq{} }
func (m *IdReq) String() string { return proto.CompactTextString(m) }
func (*IdReq) ProtoMessage()    {}
func (*IdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *IdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdReq.Unmarshal(m, b)
}
func (m *IdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdReq.Marshal(b, m, deterministic)
}
func (m *IdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdReq.Merge(m, src)
}
func (m *IdReq) XXX_Size() int {
	return xxx_messageInfo_IdReq.Size(m)
}
func (m *IdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IdReq.DiscardUnknown(m)
}

var xxx_messageInfo_IdReq proto.InternalMessageInfo

func (m *IdReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type IdsReq struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdsReq) Reset()         { *m = IdsReq{} }
func (m *IdsReq) String() string { return proto.CompactTextString(m) }
func (*IdsReq) ProtoMessage()    {}
func (*IdsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *IdsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdsReq.Unmarshal(m, b)
}
func (m *IdsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdsReq.Marshal(b, m, deterministic)
}
func (m *IdsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdsReq.Merge(m, src)
}
func (m *IdsReq) XXX_Size() int {
	return xxx_messageInfo_IdsReq.Size(m)
}
func (m *IdsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IdsReq.DiscardUnknown(m)
}

var xxx_messageInfo_IdsReq proto.InternalMessageInfo

func (m *IdsReq) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type IdsResp struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdsResp) Reset()         { *m = IdsResp{} }
func (m *IdsResp) String() string { return proto.CompactTextString(m) }
func (*IdsResp) ProtoMessage()    {}
func (*IdsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *IdsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdsResp.Unmarshal(m, b)
}
func (m *IdsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdsResp.Marshal(b, m, deterministic)
}
func (m *IdsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdsResp.Merge(m, src)
}
func (m *IdsResp) XXX_Size() int {
	return xxx_messageInfo_IdsResp.Size(m)
}
func (m *IdsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_IdsResp.DiscardUnknown(m)
}

var xxx_messageInfo_IdsResp proto.InternalMessageInfo

func (m *IdsResp) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type PageType struct {
	Current              uint32   `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	Size                 uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageType) Reset()         { *m = PageType{} }
func (m *PageType) String() string { return proto.CompactTextString(m) }
func (*PageType) ProtoMessage()    {}
func (*PageType) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *PageType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageType.Unmarshal(m, b)
}
func (m *PageType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageType.Marshal(b, m, deterministic)
}
func (m *PageType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageType.Merge(m, src)
}
func (m *PageType) XXX_Size() int {
	return xxx_messageInfo_PageType.Size(m)
}
func (m *PageType) XXX_DiscardUnknown() {
	xxx_messageInfo_PageType.DiscardUnknown(m)
}

var xxx_messageInfo_PageType proto.InternalMessageInfo

func (m *PageType) GetCurrent() uint32 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *PageType) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "social.api.ws.Empty")
	proto.RegisterType((*IdReq)(nil), "social.api.ws.IdReq")
	proto.RegisterType((*IdsReq)(nil), "social.api.ws.IdsReq")
	proto.RegisterType((*IdsResp)(nil), "social.api.ws.IdsResp")
	proto.RegisterType((*PageType)(nil), "social.api.ws.PageType")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2d, 0xce, 0x4f, 0xce, 0x4c, 0xcc,
	0xd1, 0x4b, 0x2c, 0xc8, 0xd4, 0x2b, 0x2f, 0x56, 0x62, 0xe7, 0x62, 0x75, 0xcd, 0x2d, 0x28, 0xa9,
	0x54, 0x12, 0xe7, 0x62, 0xf5, 0x4c, 0x09, 0x4a, 0x2d, 0x14, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x62, 0xca, 0x4c, 0x51, 0x92, 0xe2, 0x62, 0xf3, 0x4c, 0x29,
	0x06, 0xc9, 0x08, 0x70, 0x31, 0x67, 0xa6, 0x14, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x30, 0x07, 0x81,
	0x98, 0x4a, 0xd2, 0x5c, 0xec, 0x60, 0xb9, 0xe2, 0x02, 0x2c, 0x92, 0x16, 0x5c, 0x1c, 0x01, 0x89,
	0xe9, 0xa9, 0x21, 0x95, 0x05, 0xa9, 0x42, 0x12, 0x5c, 0xec, 0xc9, 0xa5, 0x45, 0x45, 0xa9, 0x79,
	0x25, 0x60, 0x93, 0x79, 0x83, 0x60, 0x5c, 0x21, 0x21, 0x2e, 0x96, 0xe2, 0xcc, 0xaa, 0x54, 0x09,
	0x26, 0xb0, 0x30, 0x98, 0x9d, 0xc4, 0x06, 0x76, 0xaa, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x24,
	0x36, 0xec, 0x7b, 0xba, 0x00, 0x00, 0x00,
}
