// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Key string `json:"key"`
}

type Response struct {
	Value string `json:"value"`
}

type LoginReq struct {
	UserName string `json:"user_name"`
}

type LoginResp struct {
	Passwd string `json:"passwd"`
}

type TestEmployeeUpdateReq struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}
