// Code generated by protoc-gen-go. DO NOT EDIT.
// source: err.proto

package social_api_ws

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CmdErr int32

const (
	CmdErr_RetErr CmdErr = 0
)

var CmdErr_name = map[int32]string{
	0: "RetErr",
}

var CmdErr_value = map[string]int32{
	"RetErr": 0,
}

func (x CmdErr) String() string {
	return proto.EnumName(CmdErr_name, int32(x))
}

func (CmdErr) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b4a1db73bc95ee8c, []int{0}
}

type ErrResp struct {
	// 错误编码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 错误信息
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// cmd
	OriginCmd            uint32   `protobuf:"varint,3,opt,name=origin_cmd,json=originCmd,proto3" json:"origin_cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrResp) Reset()         { *m = ErrResp{} }
func (m *ErrResp) String() string { return proto.CompactTextString(m) }
func (*ErrResp) ProtoMessage()    {}
func (*ErrResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4a1db73bc95ee8c, []int{0}
}

func (m *ErrResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrResp.Unmarshal(m, b)
}
func (m *ErrResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrResp.Marshal(b, m, deterministic)
}
func (m *ErrResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrResp.Merge(m, src)
}
func (m *ErrResp) XXX_Size() int {
	return xxx_messageInfo_ErrResp.Size(m)
}
func (m *ErrResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrResp.DiscardUnknown(m)
}

var xxx_messageInfo_ErrResp proto.InternalMessageInfo

func (m *ErrResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ErrResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ErrResp) GetOriginCmd() uint32 {
	if m != nil {
		return m.OriginCmd
	}
	return 0
}

func init() {
	proto.RegisterEnum("social.api.ws.CmdErr", CmdErr_name, CmdErr_value)
	proto.RegisterType((*ErrResp)(nil), "social.api.ws.ErrResp")
}

func init() { proto.RegisterFile("err.proto", fileDescriptor_b4a1db73bc95ee8c) }

var fileDescriptor_b4a1db73bc95ee8c = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2d, 0x2a, 0xd2,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2d, 0xce, 0x4f, 0xce, 0x4c, 0xcc, 0xd1, 0x4b, 0x2c,
	0xc8, 0xd4, 0x2b, 0x2f, 0x56, 0xf2, 0xe3, 0x62, 0x77, 0x2d, 0x2a, 0x0a, 0x4a, 0x2d, 0x2e, 0x10,
	0x12, 0xe2, 0x62, 0x49, 0xce, 0x4f, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0xb3,
	0x85, 0x04, 0xb8, 0x98, 0x73, 0x8b, 0xd3, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c,
	0x21, 0x59, 0x2e, 0xae, 0xfc, 0xa2, 0xcc, 0xf4, 0xcc, 0xbc, 0xf8, 0xe4, 0xdc, 0x14, 0x09, 0x66,
	0x05, 0x46, 0x0d, 0xde, 0x20, 0x4e, 0x88, 0x88, 0x73, 0x6e, 0x8a, 0x96, 0x08, 0x17, 0x9b, 0x73,
	0x6e, 0x8a, 0x6b, 0x51, 0x91, 0x10, 0x17, 0x17, 0x5b, 0x50, 0x6a, 0x89, 0x6b, 0x51, 0x91, 0x00,
	0x43, 0x12, 0x1b, 0xd8, 0x6e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x75, 0x22, 0x0e, 0x02,
	0x88, 0x00, 0x00, 0x00,
}
